POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre":"Luis",
    "apellido":"David",
    "correo":"admin@iteso.mx",
    "url": "https://randomuser.me/api/portraits/men/8.jpg",
    "sexo":"H",
    "fecha":"1997-05-12",
    "password":"123456",
    "admin":"true"
}

###

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "correo":"tasdf@tasdf.com",
    "password":"123456"
}

###
POST http://localhost:3000/api/users/info
Content-Type: application/json

{
    "correo":"s@s.com",
    "password":"123456"
}

###

GET http://localhost:3000/api/products
x-auth-user: yRBKvy49eV-5de6deff9694c431845c908e

###

POST http://localhost:3000/api/products
x-auth-user: yRBKvy49eV-5de6deff9694c431845c908e

###
POST http://localhost:3000/api/carrito
Content-Type: application/json
{
  "items": {
    "id": 3,
    "imagen": "https://www.steren.com.mx/media/catalog/product/cache/8a4fdc7d203276e60b54a94f4f1e185b/m/g/mg-260_x1.jpg",
    "descripcion": "Megafono",
    "categoria": "Audio",
    "cantidad": 3
  }
}
